### ISSUE TITLE
Unocss not working in NextJS 14.2.3 version

### ISSUE THREAD

**Issue by turkgenciyim** [unocss/unocss#3768]
### UnoCSS version

0.59.4

### Describe the bug

I was going to prefer unocss for a brand new start in nextjs, I created a next-app and followed the same steps to install unocss:
[unocss nextjs example](https://github.com/unocss/unocss/tree/main/examples/next#getting-started-with-unocss-and-nextjs)

But the situation is that I could not solve this error even though I did the same steps 2 times:

_note: Removing the global.css file fixes the error, so I think there is a problem in @ import or @ unocss in global css._

```
 ⨯ ./src/app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.3_@babel+core@7.24.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.3_@babel+core@7.24.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/app/globals.css
TypeError: require(...) is not a function
Import trace for requested module:
./src/app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.3_@babel+core@7.24.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.3_@babel+core@7.24.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/app/globals.css
./src/app/globals.css
```

### Reproduction

https://codesandbox.io/p/devbox/exciting-haslett-w8dny8?file=%2Fpackage.json%3A14%2C23

### System Info

Windows 10
NodeJS > 20
Next 14.2.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by linkscope** [comment]
I have the same issue,  downgrade `unocss` and `@unocss/postcss` to `0.58.9` is works.

**Comment by sibbng** [comment]
#3380 changed the behavior of how CJS module is resolved. I took a quick look at it but I don't know how we could fix/restore the previous behavior. 

Similar issue: #3724. They solved the issue by moving the config file to ESM format but I don't think this is possible for Next.js. If I remember correctly Next.js was very strict about PostCSS config format.

/cc @kwaa @userquin

**Comment by kwaa** [comment]
> I don't think this is possible for Next.js. If I remember correctly Next.js was very strict about PostCSS config format.

It looks like next.js@^14.2.0-canary.25 already supports PostCSS ESM Config.

https://github.com/vercel/next.js/issues/34448#issuecomment-2002513315
https://github.com/vercel/next.js/pull/63109

**Comment by kwaa** [comment]
It looks like Next.js is still trying to `require` instead of `import` despite the PostCSS ESM Config, and there's nothing I can do about it.

```bash
An error occurred in `next/font`.

TypeError: require(...) is not a function
    at /workspaces/sandbox/node_modules/.pnpm/next@14.2.1_@babel+core@7.24.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:62:63
    at plugin (/workspaces/sandbox/node_modules/.pnpm/next@14.2.1_@babel+core@7.24.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:30:44)
    at Processor.normalize (/workspaces/sandbox/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/processor.js:18:13)
    at new Processor (/workspaces/sandbox/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/processor.js:11:25)
    at postcss (/workspaces/sandbox/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/postcss.js:26:10)
    at /workspaces/sandbox/node_modules/.pnpm/next@14.2.1_@babel+core@7.24.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/config/blocks/css/index.js:127:37
    at async /workspaces/sandbox/node_modules/.pnpm/next@14.2.1_@babel+core@7.24.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:86:33
    at async Span.traceAsyncFn (/workspaces/sandbox/node_modules/.pnpm/next@14.2.1_@babel+core@7.24.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:154:20)
```

**Comment by userquin** [comment]
The problem is the default export in cjs, we need to use `export = <default_export>` in d.ts and d.cts files. I send a PR to fix all dual esm/cjs packages, check https://github.com/unocss/unocss/pull/3750

**Comment by turkgenciyim** [comment]
> I have the same issue, downgrade `unocss` and `@unocss/postcss` to `0.58.9` is works.

This worked for me, thanks a lot!

**Comment by after9** [comment]
> The problem is the default export in cjs, we need to use `export = <default_export>` in d.ts and d.cts files. I send a PR to fix all dual esm/cjs packages, check #3750

I think the issue is fixed now. It work all ok for me following [this](https://github.com/unocss/unocss/tree/main/examples/next#getting-started-with-unocss-and-nextjs) 

Node: v20.14.0
Next: V14.2.5
unocss: 0.61.5

Thanks!

**Comment by idootop** [comment]
Fixed by updating the PostCSS ESM configuration file:
- `postcss.config.js` 👉 `postcss.config.mjs`
- `module.exports =  {...}` 👉 `export default {...}`

<img width="482" alt="图片" src="https://github.com/user-attachments/assets/1529afc1-e409-4260-bea4-2f3ab004d376">
