### ISSUE TITLE
json icon collections import not working in 65.5.0

### ISSUE THREAD

**Issue by lumosminima** [unocss/unocss#4431]
### UnoCSS version

65.5.0

### Describe the bug

I get error `Cannot find module '@iconify-json/material-symbols/icons.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.ts(2732)` but this error also happens on 65.4.3 but icons are working. My tsconfig already has --resolveJsonModule and I tried adding json assert but icons still don't match.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-ktdq1gwd?file=src%2FApp.vue

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Use `ms` directly under `collections` (https://stackblitz.com/edit/unocss-unocss-ubhaqgu1?file=uno.config.ts,tsconfig.json,src%2FApp.vue):
```js
      collections: {
        ms: () =>
          import('@iconify-json/material-symbols/icons.json').then(
            (i) => i.default
          ),
        /*collections: {
          ms: () =>
            import('@iconify-json/material-symbols/icons.json').then(
              (i) => i.default.icons
            ),
        },*/
      },
```

**Comment by lumosminima** [comment]
🤦I made a typo and I see it works now so I'll look into a better repro cause the error still happens locally. I'm using pnpm workspaces and have a seperate `preset-icon-alias` package exported from a workspace package which I import in my main app using ` "@designsystem/css": "workspace:*"` Preset is simply aliases:
```TS
// preset-icon-alias.ts
import { PresetOrFactory } from 'unocss';
import type { Theme } from 'unocss/preset-uno';

const icons = {
'i-label': 'i-ms-label-outline',
'i-date': 'i-ms-calendar-add-on',
'i-mail': 'i-ms-mail-outline'
...
};
export default function presetIconAlias(): PresetOrFactory<Theme> {
	return {
		name: 'uno-icon-alias',
		shortcuts: icons,
		safelist: Object.keys(icons),
	};
}
```
on the cli after running dev server I get this error in the project I import:
```
Failed to load custom icon "mail-outline" in "ms": TypeError [ERR_IMPORT_ATTRIBUTE_MISSING]: Module "file:///home/user/nix/projects/myproject/node_modules/.pnpm/@iconify-json+material-symbols@1.2.14/node_modules/@iconify-json/material-symbols/icons.json" needs an import attribute of "type: json"
    at validateAttributes (node:internal/modules/esm/assert:88:15)
    at defaultLoad (node:internal/modules/esm/load:129:3)
    at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:519:32)
    at async ModuleJob._link (node:internal/modules/esm/module_job:115:19) {
  code: 'ERR_IMPORT_ATTRIBUTE_MISSING'
```
But the same setup works fine if I downgrade.
