### ISSUE TITLE
[unocss/vite] Dist-Chunk mode no longer works with vite 6.3

### ISSUE THREAD

**Issue by jimmy-sc** [unocss/unocss#4597]
### UnoCSS version

v66.1.0-beta.11

### Describe the bug

With vite version 6.3 the dist-chunk mode no longer works. Vite build gives the following error message:

```
> vite build

vite v6.3.0 building for production...
✓ 576 modules transformed.
[unocss] writing css to main-!~{004}~.js.css { handler: [AsyncFunction: handler] }
✗ Build failed in 947ms
error during build:
[unocss:chunk] cssPlugin.transform is not a function...
```

This seems to be happening due to the api change from this commit introduced in vite 6.3:
https://github.com/vitejs/vite/pull/19586

I am not sure if anything is affected by this. For the dist-chunk mode I guess the only change needed, is to call the transform hook in the chunk-build.ts like this

```
 await cssPlugin!.transform.handler(css, fakeCssId)
```

### Reproduction

Use dist-chunk mode and try to build with vite version 6.3

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
We added a patch on Vite side for now. It should be working with 6.3.1.

On unocss side, #4598 should make the implementation a bit more future-proof.
