### ISSUE TITLE
Unocss({ presets: [presetWind()] }) is kaput after upgrade

### ISSUE THREAD

**Issue by millette** [unocss/unocss#1933]
After I upgraded to 0.47.1 the build stopped working but dev still works.

I received this error:

```
vite.config.ts:20:24 - error TS2322: Type 'Preset<Theme>' is not assignable to type 'Preset<Theme> | Preset<Theme>[]'.
  Type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.47.1/node_modules/@unocss/core/dist/index").Preset<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>' is not assignable to type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.46.5/node_modules/@unocss/core/dist/index").Preset<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>'.
    Types of property 'rules' are incompatible.
      Type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.47.1/node_modules/@unocss/core/dist/index").Rule<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>[]' is not assignable to type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.46.5/node_modules/@unocss/core/dist/index").Rule<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>[]'.
        Type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.47.1/node_modules/@unocss/core/dist/index").Rule<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>' is not assignable to type 'import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+core@0.46.5/node_modules/@unocss/core/dist/index").Rule<import("/home/millette/travail/chacre/digigolf-raster/node_modules/.pnpm/@unocss+preset-mini@0.47.1/node_modules/@unocss/preset-mini/dist/types-3bfb4dc5").T>'.
          Type '[RegExp, DynamicMatcher<Theme>]' is not assignable to type 'Rule<Theme>'.
            Type '[RegExp, DynamicMatcher<Theme>]' is not assignable to type '[string, CSSObject | CSSEntries]'.
              Type at position 0 in source is not compatible with type at position 0 in target.
                Type 'RegExp' is not assignable to type 'string'.

20     Unocss({ presets: [presetWind()] }),
                          ~~~~~~~~~~~~


Found 1 error in vite.config.ts:20

 ELIFECYCLE  Command failed with exit code 2.
```

My vite.config.ts:

```ts
// core
import { resolve } from "node:path"

// npm
import presetWind from "@unocss/preset-wind"
import Unocss from "@unocss/vite"

import { defineConfig } from "vite"
import solidPlugin from "vite-plugin-solid"

export default defineConfig({
  resolve: {
    alias: {
      "~/": `${resolve(__dirname, "src")}/`,
    },
  },
  base: "./",
  plugins: [
    solidPlugin(),
    Unocss({ presets: [presetWind()] }),
  ],
  build: {
    target: "esnext",
    minify: "terser",
  },
})
```

And package.json:

```json
{
  "name": "digigolf-raster",
  "version": "0.0.0",
  "description": "DigiGolf Raster, pixels galore!",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "lint": "tsc --noEmit --skipLibCheck",
    "build": "tsc --noEmit --skipLibCheck && vite build",
    "serve": "vite preview",
    "format": "dprint fmt \"**/*.{ts,tsx,css,md,json}\"",
    "posttest": "npm run format",
    "prepare": "husky install"
  },
  "devDependencies": {
    "@types/node": "^18.11.9",
    "@unocss/preset-wind": "0.47.1",
    "@unocss/vite": "^0.46.5",
    "dprint": "^0.33.0",
    "husky": "^8.0.2",
    "lint-staged": "^13.0.4",
    "prettier": "^2.8.0",
    "terser": "^5.16.0",
    "typescript": "^4.9.3",
    "vite": "^3.2.4",
    "vite-plugin-solid": "^2.4.0"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.5.1",
    "@unocss/reset": "0.47.1",
    "load-json-file": "^7.0.1",
    "solid-js": "^1.6.2",
    "unocss": "0.47.1",
    "write-json-file": "^5.0.0"
  },
  "lint-staged": {
    "*.{ts,tsx,css,md,json}": "dprint fmt"
  }
}
```

**Comment by sibbng** [comment]
You have mismatching version of unocss packages
```json
    "@unocss/preset-wind": "0.47.1",
    "@unocss/vite": "^0.46.5",
```

You need to upgrade both.

**Comment by millette** [comment]
Oh, I see what happened, thanks!
